### Site Settings ###
title               : Haotian Sun
description         : >-                               # >- means to ignore newlines until "url:"
                      Software Engineer and Product Manager.
                      Basketball :basketball:, Fitness :muscle:, and Music Technology :musical_keyboard:.

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : htsunnn/htsunnn.github.io   # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Haotian Sun
  image             : https://i.ibb.co/CVRQNSn/Wechat-IMG59.jpg
# behance           : haotiansun96@gmail.com
# dribbble          : your_username
  email             : haotiansun96@gmail.com
  facebook          : profile.php?id=100012949785806
  github            : haotiansun
# gitlab            : your_username
# instagram         : aaaddii__10
  linkedin          : haotiansunn
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : AdityaAnil19
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock